/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.vanderlei.telas;

/**
 *
 * @author vande
 */

import java.sql.*;
import br.com.vanderlei.dal.Modulo_de_conexao;
import javax.swing.JOptionPane;
public class Tela_usuarios extends javax.swing.JInternalFrame {

     
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet sr = null;
   
    public Tela_usuarios() {
        initComponents();
        conexao = Modulo_de_conexao.conector();
    }

    private void adicionar_dados(){
        String sql = "insert into tbusuario(iduser,usuario,fone,login,senha,perfil) values(?,?,?,?,?,?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,edit_id_usuario_.getText());
            pst.setString(2,edit_id_nome_.getText());
            pst.setString(3,edit_id_fone_.getText());
            pst.setString(4,edit_id_login_.getText());
            pst.setString(5,edit_id_senha_.getText());
            pst.setString(6,jComboBox1_id_usuario_.getSelectedItem().toString());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Usuario inserido com sucesso!");
                edit_id_nome_.setText(null);
                edit_id_fone_.setText(null);
                edit_id_login_.setText(null);
                edit_id_senha_.setText(null);
                jComboBox1_id_usuario_.setSelectedItem(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            
        }
    }
    
    
    private void consultar(){
        String sql = "select * from tbusuario where  iduser=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1,edit_id_usuario_.getText());
            sr = pst.executeQuery();
            if (sr.next()) {
                edit_id_nome_.setText(sr.getString(2));
                edit_id_fone_.setText(sr.getString(3));
                edit_id_login_.setText(sr.getString(4));
                edit_id_senha_.setText(sr.getString(5));
                jComboBox1_id_usuario_.setSelectedItem(sr.getString(6));
            } else {
                JOptionPane.showMessageDialog(null,"Não existe usuario com este id");
                edit_id_nome_.setText(null);
                edit_id_fone_.setText(null);
                edit_id_login_.setText(null);
                edit_id_senha_.setText(null);
                jComboBox1_id_usuario_.setSelectedItem(null);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edit_id_usuario_ = new javax.swing.JTextField();
        edit_id_nome_ = new javax.swing.JTextField();
        edit_id_login_ = new javax.swing.JTextField();
        edit_id_senha_ = new javax.swing.JTextField();
        jComboBox1_id_usuario_ = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        edit_id_fone_ = new javax.swing.JTextField();
        btn_adicionar_usu = new javax.swing.JButton();
        btn_pesqui_usu = new javax.swing.JButton();
        btn_update_usu = new javax.swing.JButton();
        btn_deletar_usu = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuario");
        setPreferredSize(new java.awt.Dimension(640, 480));

        jLabel1.setText("Id");

        jLabel2.setText("Nome");

        jLabel3.setText("Login");

        jLabel4.setText("senha");

        jLabel5.setText("Perfil");

        edit_id_usuario_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_id_usuario_ActionPerformed(evt);
            }
        });

        edit_id_nome_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_id_nome_ActionPerformed(evt);
            }
        });

        jComboBox1_id_usuario_.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "adimin", "user" }));

        jLabel6.setText("Fone");

        edit_id_fone_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_id_fone_ActionPerformed(evt);
            }
        });

        btn_adicionar_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vanderlei/icones/aedicionar.png"))); // NOI18N
        btn_adicionar_usu.setToolTipText("adicionar");
        btn_adicionar_usu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_adicionar_usu.setPreferredSize(new java.awt.Dimension(80, 80));
        btn_adicionar_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionar_usuActionPerformed(evt);
            }
        });

        btn_pesqui_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vanderlei/icones/pesquisar.png"))); // NOI18N
        btn_pesqui_usu.setToolTipText("pesquisar");
        btn_pesqui_usu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pesqui_usu.setPreferredSize(new java.awt.Dimension(80, 80));
        btn_pesqui_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesqui_usuActionPerformed(evt);
            }
        });

        btn_update_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vanderlei/icones/update.png"))); // NOI18N
        btn_update_usu.setToolTipText("atualizar");
        btn_update_usu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update_usu.setPreferredSize(new java.awt.Dimension(80, 80));

        btn_deletar_usu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/vanderlei/icones/apagar.png"))); // NOI18N
        btn_deletar_usu.setToolTipText("deletar");
        btn_deletar_usu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deletar_usu.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edit_id_nome_)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_adicionar_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(btn_pesqui_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(edit_id_senha_, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                            .addComponent(edit_id_fone_))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edit_id_login_)
                                    .addComponent(jComboBox1_id_usuario_, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(btn_update_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addComponent(btn_deletar_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edit_id_usuario_, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edit_id_usuario_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edit_id_nome_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edit_id_fone_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edit_id_login_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1_id_usuario_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(edit_id_senha_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adicionar_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pesqui_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deletar_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        setBounds(0, 0, 640, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void edit_id_usuario_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_id_usuario_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_id_usuario_ActionPerformed

    private void edit_id_nome_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_id_nome_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_id_nome_ActionPerformed

    private void edit_id_fone_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_id_fone_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_id_fone_ActionPerformed

    private void btn_pesqui_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesqui_usuActionPerformed
        // TODO add your handling code here:
        consultar();
        
    }//GEN-LAST:event_btn_pesqui_usuActionPerformed

    private void btn_adicionar_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionar_usuActionPerformed
        // TODO add your handling code here:
         adicionar_dados();
    }//GEN-LAST:event_btn_adicionar_usuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar_usu;
    private javax.swing.JButton btn_deletar_usu;
    private javax.swing.JButton btn_pesqui_usu;
    private javax.swing.JButton btn_update_usu;
    private javax.swing.JTextField edit_id_fone_;
    private javax.swing.JTextField edit_id_login_;
    private javax.swing.JTextField edit_id_nome_;
    private javax.swing.JTextField edit_id_senha_;
    private javax.swing.JTextField edit_id_usuario_;
    private javax.swing.JComboBox jComboBox1_id_usuario_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
